// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: box/file.proto

package eboxpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FileCategory int32

const (
	FileCategory_All      FileCategory = 0 // 全部
	FileCategory_Image    FileCategory = 1 // 图片
	FileCategory_Video    FileCategory = 2 // 视频
	FileCategory_Audio    FileCategory = 3 // 音频
	FileCategory_Document FileCategory = 4 // 文档
	FileCategory_Other    FileCategory = 5 // 其它文件
)

// Enum value maps for FileCategory.
var (
	FileCategory_name = map[int32]string{
		0: "All",
		1: "Image",
		2: "Video",
		3: "Audio",
		4: "Document",
		5: "Other",
	}
	FileCategory_value = map[string]int32{
		"All":      0,
		"Image":    1,
		"Video":    2,
		"Audio":    3,
		"Document": 4,
		"Other":    5,
	}
)

func (x FileCategory) Enum() *FileCategory {
	p := new(FileCategory)
	*p = x
	return p
}

func (x FileCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_box_file_proto_enumTypes[0].Descriptor()
}

func (FileCategory) Type() protoreflect.EnumType {
	return &file_box_file_proto_enumTypes[0]
}

func (x FileCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileCategory.Descriptor instead.
func (FileCategory) EnumDescriptor() ([]byte, []int) {
	return file_box_file_proto_rawDescGZIP(), []int{0}
}

type FileSource int32

const (
	FileSource_None       FileSource = 0
	FileSource_AutoBackup FileSource = 1
	FileSource_Manual     FileSource = 2
	FileSource_Message    FileSource = 3
)

// Enum value maps for FileSource.
var (
	FileSource_name = map[int32]string{
		0: "None",
		1: "AutoBackup",
		2: "Manual",
		3: "Message",
	}
	FileSource_value = map[string]int32{
		"None":       0,
		"AutoBackup": 1,
		"Manual":     2,
		"Message":    3,
	}
)

func (x FileSource) Enum() *FileSource {
	p := new(FileSource)
	*p = x
	return p
}

func (x FileSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileSource) Descriptor() protoreflect.EnumDescriptor {
	return file_box_file_proto_enumTypes[1].Descriptor()
}

func (FileSource) Type() protoreflect.EnumType {
	return &file_box_file_proto_enumTypes[1]
}

func (x FileSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileSource.Descriptor instead.
func (FileSource) EnumDescriptor() ([]byte, []int) {
	return file_box_file_proto_rawDescGZIP(), []int{1}
}

type UploadCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//文件路径
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	//文件MD5
	Md5 string `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	//文件名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	//视频或者图片的宽度
	Width int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	//视频或者图片的高度
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	//视频或音频消息播放时间，单位毫秒
	PlayMillisecond int64 `protobuf:"varint,6,opt,name=play_millisecond,json=playMillisecond,proto3" json:"play_millisecond,omitempty"`
	//文件的大小，单位byte
	ByteSize int64 `protobuf:"varint,7,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	//文件来源
	Source FileSource `protobuf:"varint,8,opt,name=source,proto3,enum=etsme.ebox.file.FileSource" json:"source,omitempty"`
}

func (x *UploadCompleteRequest) Reset() {
	*x = UploadCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCompleteRequest) ProtoMessage() {}

func (x *UploadCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCompleteRequest.ProtoReflect.Descriptor instead.
func (*UploadCompleteRequest) Descriptor() ([]byte, []int) {
	return file_box_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadCompleteRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UploadCompleteRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *UploadCompleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadCompleteRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UploadCompleteRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UploadCompleteRequest) GetPlayMillisecond() int64 {
	if x != nil {
		return x.PlayMillisecond
	}
	return 0
}

func (x *UploadCompleteRequest) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *UploadCompleteRequest) GetSource() FileSource {
	if x != nil {
		return x.Source
	}
	return FileSource_None
}

var File_box_file_proto protoreflect.FileDescriptor

var file_box_file_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x6f, 0x78, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0xfa, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x64, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x6c, 0x61,
	0x79, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x79, 0x74, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x62, 0x79, 0x74, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x65, 0x74, 0x73, 0x6d,
	0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2a, 0x51,
	0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x07,
	0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x10,
	0x05, 0x2a, 0x3f, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x75, 0x74,
	0x6f, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x61, 0x6e,
	0x75, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x10, 0x03, 0x42, 0x5e, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x62, 0x6f, 0x78, 0x42, 0x09, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x65, 0x74, 0x73, 0x75, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x65, 0x62, 0x6f, 0x78,
	0x2f, 0x65, 0x62, 0x6f, 0x78, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x65, 0x62, 0x6f, 0x78, 0x70, 0x62, 0xf8, 0x01, 0x01, 0xa2, 0x02, 0x05, 0x45, 0x50, 0x42,
	0x6f, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_box_file_proto_rawDescOnce sync.Once
	file_box_file_proto_rawDescData = file_box_file_proto_rawDesc
)

func file_box_file_proto_rawDescGZIP() []byte {
	file_box_file_proto_rawDescOnce.Do(func() {
		file_box_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_box_file_proto_rawDescData)
	})
	return file_box_file_proto_rawDescData
}

var file_box_file_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_box_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_box_file_proto_goTypes = []interface{}{
	(FileCategory)(0),             // 0: etsme.ebox.file.FileCategory
	(FileSource)(0),               // 1: etsme.ebox.file.FileSource
	(*UploadCompleteRequest)(nil), // 2: etsme.ebox.file.UploadCompleteRequest
}
var file_box_file_proto_depIdxs = []int32{
	1, // 0: etsme.ebox.file.UploadCompleteRequest.source:type_name -> etsme.ebox.file.FileSource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_box_file_proto_init() }
func file_box_file_proto_init() {
	if File_box_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_box_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_box_file_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_box_file_proto_goTypes,
		DependencyIndexes: file_box_file_proto_depIdxs,
		EnumInfos:         file_box_file_proto_enumTypes,
		MessageInfos:      file_box_file_proto_msgTypes,
	}.Build()
	File_box_file_proto = out.File
	file_box_file_proto_rawDesc = nil
	file_box_file_proto_goTypes = nil
	file_box_file_proto_depIdxs = nil
}
