// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: box/gateway.proto

package eboxpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GtwOperationId int32

const (
	GtwOperationId_DEFAULT           GtwOperationId = 0
	GtwOperationId_CHANGEENV         GtwOperationId = 1
	GtwOperationId_UPGRADEBIGVERSION GtwOperationId = 2
	GtwOperationId_UPGRADESTATUS     GtwOperationId = 3
	GtwOperationId_NODEID            GtwOperationId = 4
	GtwOperationId_DEVSTATUS         GtwOperationId = 5
)

// Enum value maps for GtwOperationId.
var (
	GtwOperationId_name = map[int32]string{
		0: "DEFAULT",
		1: "CHANGEENV",
		2: "UPGRADEBIGVERSION",
		3: "UPGRADESTATUS",
		4: "NODEID",
		5: "DEVSTATUS",
	}
	GtwOperationId_value = map[string]int32{
		"DEFAULT":           0,
		"CHANGEENV":         1,
		"UPGRADEBIGVERSION": 2,
		"UPGRADESTATUS":     3,
		"NODEID":            4,
		"DEVSTATUS":         5,
	}
)

func (x GtwOperationId) Enum() *GtwOperationId {
	p := new(GtwOperationId)
	*p = x
	return p
}

func (x GtwOperationId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GtwOperationId) Descriptor() protoreflect.EnumDescriptor {
	return file_box_gateway_proto_enumTypes[0].Descriptor()
}

func (GtwOperationId) Type() protoreflect.EnumType {
	return &file_box_gateway_proto_enumTypes[0]
}

func (x GtwOperationId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GtwOperationId.Descriptor instead.
func (GtwOperationId) EnumDescriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{0}
}

type GtwUpdaterContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     int32             `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	Env        *UpdaterChangeEnv `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	Packageloc string            `protobuf:"bytes,3,opt,name=packageloc,proto3" json:"packageloc,omitempty"`
	Version    string            `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Appname    string            `protobuf:"bytes,5,opt,name=appname,proto3" json:"appname,omitempty"`
}

func (x *GtwUpdaterContext) Reset() {
	*x = GtwUpdaterContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtwUpdaterContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtwUpdaterContext) ProtoMessage() {}

func (x *GtwUpdaterContext) ProtoReflect() protoreflect.Message {
	mi := &file_box_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtwUpdaterContext.ProtoReflect.Descriptor instead.
func (*GtwUpdaterContext) Descriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GtwUpdaterContext) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *GtwUpdaterContext) GetEnv() *UpdaterChangeEnv {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *GtwUpdaterContext) GetPackageloc() string {
	if x != nil {
		return x.Packageloc
	}
	return ""
}

func (x *GtwUpdaterContext) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GtwUpdaterContext) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

type UpdaterChangeEnv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planeturl string `protobuf:"bytes,1,opt,name=planeturl,proto3" json:"planeturl,omitempty"`
	Eboxurl   string `protobuf:"bytes,2,opt,name=eboxurl,proto3" json:"eboxurl,omitempty"`
}

func (x *UpdaterChangeEnv) Reset() {
	*x = UpdaterChangeEnv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdaterChangeEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdaterChangeEnv) ProtoMessage() {}

func (x *UpdaterChangeEnv) ProtoReflect() protoreflect.Message {
	mi := &file_box_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdaterChangeEnv.ProtoReflect.Descriptor instead.
func (*UpdaterChangeEnv) Descriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *UpdaterChangeEnv) GetPlaneturl() string {
	if x != nil {
		return x.Planeturl
	}
	return ""
}

func (x *UpdaterChangeEnv) GetEboxurl() string {
	if x != nil {
		return x.Eboxurl
	}
	return ""
}

type GtwApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation     GtwOperationId `protobuf:"varint,1,opt,name=operation,proto3,enum=etsme.ebox.gateway.GtwOperationId" json:"operation,omitempty"`
	Content       []byte         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ServerVersion int32          `protobuf:"varint,3,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
}

func (x *GtwApiRequest) Reset() {
	*x = GtwApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtwApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtwApiRequest) ProtoMessage() {}

func (x *GtwApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtwApiRequest.ProtoReflect.Descriptor instead.
func (*GtwApiRequest) Descriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GtwApiRequest) GetOperation() GtwOperationId {
	if x != nil {
		return x.Operation
	}
	return GtwOperationId_DEFAULT
}

func (x *GtwApiRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GtwApiRequest) GetServerVersion() int32 {
	if x != nil {
		return x.ServerVersion
	}
	return 0
}

type GtwApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation GtwOperationId `protobuf:"varint,1,opt,name=operation,proto3,enum=etsme.ebox.gateway.GtwOperationId" json:"operation,omitempty"`
	Content   []byte         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Message   string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Code      int32          `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GtwApiResponse) Reset() {
	*x = GtwApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtwApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtwApiResponse) ProtoMessage() {}

func (x *GtwApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtwApiResponse.ProtoReflect.Descriptor instead.
func (*GtwApiResponse) Descriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GtwApiResponse) GetOperation() GtwOperationId {
	if x != nil {
		return x.Operation
	}
	return GtwOperationId_DEFAULT
}

func (x *GtwApiResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GtwApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GtwApiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GtwUpdaterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Process int32  `protobuf:"varint,3,opt,name=process,proto3" json:"process,omitempty"`
	Need    bool   `protobuf:"varint,4,opt,name=need,proto3" json:"need,omitempty"`
}

func (x *GtwUpdaterResponse) Reset() {
	*x = GtwUpdaterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtwUpdaterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtwUpdaterResponse) ProtoMessage() {}

func (x *GtwUpdaterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtwUpdaterResponse.ProtoReflect.Descriptor instead.
func (*GtwUpdaterResponse) Descriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GtwUpdaterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GtwUpdaterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GtwUpdaterResponse) GetProcess() int32 {
	if x != nil {
		return x.Process
	}
	return 0
}

func (x *GtwUpdaterResponse) GetNeed() bool {
	if x != nil {
		return x.Need
	}
	return false
}

type GtwDevStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Cpuidle int32  `protobuf:"varint,3,opt,name=cpuidle,proto3" json:"cpuidle,omitempty"`
	Memfree int32  `protobuf:"varint,4,opt,name=memfree,proto3" json:"memfree,omitempty"`
	Temp    int32  `protobuf:"varint,5,opt,name=temp,proto3" json:"temp,omitempty"`
}

func (x *GtwDevStatusResponse) Reset() {
	*x = GtwDevStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtwDevStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtwDevStatusResponse) ProtoMessage() {}

func (x *GtwDevStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtwDevStatusResponse.ProtoReflect.Descriptor instead.
func (*GtwDevStatusResponse) Descriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GtwDevStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GtwDevStatusResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GtwDevStatusResponse) GetCpuidle() int32 {
	if x != nil {
		return x.Cpuidle
	}
	return 0
}

func (x *GtwDevStatusResponse) GetMemfree() int32 {
	if x != nil {
		return x.Memfree
	}
	return 0
}

func (x *GtwDevStatusResponse) GetTemp() int32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

type GtwNetInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Nodeid string `protobuf:"bytes,3,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
}

func (x *GtwNetInfoResponse) Reset() {
	*x = GtwNetInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GtwNetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GtwNetInfoResponse) ProtoMessage() {}

func (x *GtwNetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GtwNetInfoResponse.ProtoReflect.Descriptor instead.
func (*GtwNetInfoResponse) Descriptor() ([]byte, []int) {
	return file_box_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GtwNetInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GtwNetInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GtwNetInfoResponse) GetNodeid() string {
	if x != nil {
		return x.Nodeid
	}
	return ""
}

var File_box_gateway_proto protoreflect.FileDescriptor

var file_box_gateway_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x6f, 0x78, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0xb7, 0x01, 0x0a, 0x11, 0x47, 0x74, 0x77, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x76, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x1e, 0x0a,
	0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x6c, 0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x6c, 0x6f, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x4a, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x45, 0x6e, 0x76, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74,
	0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x62, 0x6f, 0x78, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x62, 0x6f, 0x78, 0x75, 0x72, 0x6c, 0x22, 0x91, 0x01,
	0x0a, 0x0d, 0x47, 0x74, 0x77, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x40, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x74, 0x77, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x47, 0x74, 0x77, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e,
	0x65, 0x62, 0x6f, 0x78, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x74, 0x77,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x68,
	0x0a, 0x12, 0x47, 0x74, 0x77, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x6e, 0x65, 0x65, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x14, 0x47, 0x74, 0x77,
	0x44, 0x65, 0x76, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x70, 0x75, 0x69, 0x64,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x70, 0x75, 0x69, 0x64, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x66, 0x72, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x66, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x22,
	0x52, 0x0a, 0x12, 0x47, 0x74, 0x77, 0x4e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x69, 0x64, 0x2a, 0x71, 0x0a, 0x0e, 0x47, 0x74, 0x77, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x45, 0x4e, 0x56, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x50, 0x47, 0x52, 0x41, 0x44, 0x45, 0x42, 0x49, 0x47, 0x56,
	0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x50, 0x47, 0x52,
	0x41, 0x44, 0x45, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4e,
	0x4f, 0x44, 0x45, 0x49, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x56, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x10, 0x05, 0x42, 0x5c, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x74,
	0x73, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x62, 0x6f, 0x78,
	0x42, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x65, 0x74, 0x73, 0x75, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x65, 0x62,
	0x6f, 0x78, 0x2f, 0x65, 0x62, 0x6f, 0x78, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x65, 0x62, 0x6f, 0x78, 0x70, 0x62, 0xf8, 0x01, 0x01, 0xa2, 0x02, 0x05, 0x45,
	0x50, 0x42, 0x6f, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_box_gateway_proto_rawDescOnce sync.Once
	file_box_gateway_proto_rawDescData = file_box_gateway_proto_rawDesc
)

func file_box_gateway_proto_rawDescGZIP() []byte {
	file_box_gateway_proto_rawDescOnce.Do(func() {
		file_box_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_box_gateway_proto_rawDescData)
	})
	return file_box_gateway_proto_rawDescData
}

var file_box_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_box_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_box_gateway_proto_goTypes = []interface{}{
	(GtwOperationId)(0),          // 0: etsme.ebox.gateway.GtwOperationId
	(*GtwUpdaterContext)(nil),    // 1: etsme.ebox.gateway.GtwUpdaterContext
	(*UpdaterChangeEnv)(nil),     // 2: etsme.ebox.gateway.UpdaterChangeEnv
	(*GtwApiRequest)(nil),        // 3: etsme.ebox.gateway.GtwApiRequest
	(*GtwApiResponse)(nil),       // 4: etsme.ebox.gateway.GtwApiResponse
	(*GtwUpdaterResponse)(nil),   // 5: etsme.ebox.gateway.GtwUpdaterResponse
	(*GtwDevStatusResponse)(nil), // 6: etsme.ebox.gateway.GtwDevStatusResponse
	(*GtwNetInfoResponse)(nil),   // 7: etsme.ebox.gateway.GtwNetInfoResponse
}
var file_box_gateway_proto_depIdxs = []int32{
	2, // 0: etsme.ebox.gateway.GtwUpdaterContext.env:type_name -> etsme.ebox.gateway.UpdaterChangeEnv
	0, // 1: etsme.ebox.gateway.GtwApiRequest.operation:type_name -> etsme.ebox.gateway.GtwOperationId
	0, // 2: etsme.ebox.gateway.GtwApiResponse.operation:type_name -> etsme.ebox.gateway.GtwOperationId
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_box_gateway_proto_init() }
func file_box_gateway_proto_init() {
	if File_box_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_box_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtwUpdaterContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdaterChangeEnv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtwApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtwApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtwUpdaterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtwDevStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GtwNetInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_box_gateway_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_box_gateway_proto_goTypes,
		DependencyIndexes: file_box_gateway_proto_depIdxs,
		EnumInfos:         file_box_gateway_proto_enumTypes,
		MessageInfos:      file_box_gateway_proto_msgTypes,
	}.Build()
	File_box_gateway_proto = out.File
	file_box_gateway_proto_rawDesc = nil
	file_box_gateway_proto_goTypes = nil
	file_box_gateway_proto_depIdxs = nil
}
