// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: box/im.proto

package eboxpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InstantMessage_MessageType int32

const (
	InstantMessage_TEXT         InstantMessage_MessageType = 0
	InstantMessage_AUDIO        InstantMessage_MessageType = 1
	InstantMessage_IMAGE        InstantMessage_MessageType = 2
	InstantMessage_VIDEO        InstantMessage_MessageType = 3
	InstantMessage_IMAGE_LIST   InstantMessage_MessageType = 4
	InstantMessage_NOTIFICATION InstantMessage_MessageType = 5 // 时间，通知类的消息，没有发送人。通常至于一段文本展示
	InstantMessage_FILE         InstantMessage_MessageType = 6
)

// Enum value maps for InstantMessage_MessageType.
var (
	InstantMessage_MessageType_name = map[int32]string{
		0: "TEXT",
		1: "AUDIO",
		2: "IMAGE",
		3: "VIDEO",
		4: "IMAGE_LIST",
		5: "NOTIFICATION",
		6: "FILE",
	}
	InstantMessage_MessageType_value = map[string]int32{
		"TEXT":         0,
		"AUDIO":        1,
		"IMAGE":        2,
		"VIDEO":        3,
		"IMAGE_LIST":   4,
		"NOTIFICATION": 5,
		"FILE":         6,
	}
)

func (x InstantMessage_MessageType) Enum() *InstantMessage_MessageType {
	p := new(InstantMessage_MessageType)
	*p = x
	return p
}

func (x InstantMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstantMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_box_im_proto_enumTypes[0].Descriptor()
}

func (InstantMessage_MessageType) Type() protoreflect.EnumType {
	return &file_box_im_proto_enumTypes[0]
}

func (x InstantMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstantMessage_MessageType.Descriptor instead.
func (InstantMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{2, 0}
}

type ListConversationMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	StartMid       string `protobuf:"bytes,2,opt,name=start_mid,json=startMid,proto3" json:"start_mid,omitempty"`
	Limit          int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Later          bool   `protobuf:"varint,4,opt,name=later,proto3" json:"later,omitempty"`
	//是否包含当前消息
	Include bool  `protobuf:"varint,5,opt,name=include,proto3" json:"include,omitempty"`
	Uid     int64 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ListConversationMessageRequest) Reset() {
	*x = ListConversationMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConversationMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationMessageRequest) ProtoMessage() {}

func (x *ListConversationMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationMessageRequest.ProtoReflect.Descriptor instead.
func (*ListConversationMessageRequest) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{0}
}

func (x *ListConversationMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListConversationMessageRequest) GetStartMid() string {
	if x != nil {
		return x.StartMid
	}
	return ""
}

func (x *ListConversationMessageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationMessageRequest) GetLater() bool {
	if x != nil {
		return x.Later
	}
	return false
}

func (x *ListConversationMessageRequest) GetInclude() bool {
	if x != nil {
		return x.Include
	}
	return false
}

func (x *ListConversationMessageRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ListConversationMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*InstantMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Uid      int64             `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ListConversationMessageResponse) Reset() {
	*x = ListConversationMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConversationMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationMessageResponse) ProtoMessage() {}

func (x *ListConversationMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationMessageResponse.ProtoReflect.Descriptor instead.
func (*ListConversationMessageResponse) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{1}
}

func (x *ListConversationMessageResponse) GetMessages() []*InstantMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListConversationMessageResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type InstantMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//消息类型
	MessageType InstantMessage_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=etsme.ebox.InstantMessage_MessageType" json:"message_type,omitempty"`
	// 前端生成，用于做消息对应
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	//消息ID，只有发送成功以后才会有
	Mid string `protobuf:"bytes,3,opt,name=mid,proto3" json:"mid,omitempty"`
	//发送消息的用户ID
	Uid int64 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	// 昵称，也可能是备注名[发送消息不需要填写]
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像[发送消息不需要填写]
	AvatarUrl string `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// 消息的发送时间
	SendAt int64 `protobuf:"varint,7,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	// 文本消息
	Text string `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	// 消息附件
	Attachment []*Attachment `protobuf:"bytes,9,rep,name=attachment,proto3" json:"attachment,omitempty"`
	// 接受消息的会话ID
	ConversationId string `protobuf:"bytes,10,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
}

func (x *InstantMessage) Reset() {
	*x = InstantMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstantMessage) ProtoMessage() {}

func (x *InstantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstantMessage.ProtoReflect.Descriptor instead.
func (*InstantMessage) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{2}
}

func (x *InstantMessage) GetMessageType() InstantMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return InstantMessage_TEXT
}

func (x *InstantMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *InstantMessage) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *InstantMessage) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InstantMessage) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *InstantMessage) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *InstantMessage) GetSendAt() int64 {
	if x != nil {
		return x.SendAt
	}
	return 0
}

func (x *InstantMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InstantMessage) GetAttachment() []*Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *InstantMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//文件路径
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	//文件MD5
	Md5 string `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	//文件名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	//视频或者图片的宽度
	Width int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	//视频或者图片的高度
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	//视频或音频消息播放时间，单位毫秒
	PlayMillisecond int64 `protobuf:"varint,6,opt,name=play_millisecond,json=playMillisecond,proto3" json:"play_millisecond,omitempty"`
	//文件的大小，单位byte
	ByteSize int64 `protobuf:"varint,7,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	//文件来源的用户的NwID
	FromUserNwid string `protobuf:"bytes,8,opt,name=from_user_nwid,json=fromUserNwid,proto3" json:"from_user_nwid,omitempty"`
	//文件来源的用户的NodeID
	FromUserNodeId string `protobuf:"bytes,9,opt,name=from_user_node_id,json=fromUserNodeId,proto3" json:"from_user_node_id,omitempty"`
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{3}
}

func (x *Attachment) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Attachment) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attachment) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Attachment) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Attachment) GetPlayMillisecond() int64 {
	if x != nil {
		return x.PlayMillisecond
	}
	return 0
}

func (x *Attachment) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *Attachment) GetFromUserNwid() string {
	if x != nil {
		return x.FromUserNwid
	}
	return ""
}

func (x *Attachment) GetFromUserNodeId() string {
	if x != nil {
		return x.FromUserNodeId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *InstantMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Uid     int64           `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	To      int64           `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"` // 0 - to all members, otherwise used for proxy internally
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetMessage() *InstantMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendMessageRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SendMessageRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type SendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Uid int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResponse) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *SendMessageResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ReadMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Mid            string `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Uid            int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ReadMessageRequest) Reset() {
	*x = ReadMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageRequest) ProtoMessage() {}

func (x *ReadMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageRequest.ProtoReflect.Descriptor instead.
func (*ReadMessageRequest) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{6}
}

func (x *ReadMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadMessageRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *ReadMessageRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CancelSendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Mid            string `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Uid            int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	To             int64  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"` // 0 - to all members, otherwise used for proxy internally
}

func (x *CancelSendMessageRequest) Reset() {
	*x = CancelSendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSendMessageRequest) ProtoMessage() {}

func (x *CancelSendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSendMessageRequest.ProtoReflect.Descriptor instead.
func (*CancelSendMessageRequest) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{7}
}

func (x *CancelSendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CancelSendMessageRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *CancelSendMessageRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CancelSendMessageRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type ListMessageAttachmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Mid            string `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Page           int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size           int32  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListMessageAttachmentRequest) Reset() {
	*x = ListMessageAttachmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMessageAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageAttachmentRequest) ProtoMessage() {}

func (x *ListMessageAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageAttachmentRequest.ProtoReflect.Descriptor instead.
func (*ListMessageAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{8}
}

func (x *ListMessageAttachmentRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListMessageAttachmentRequest) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *ListMessageAttachmentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMessageAttachmentRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMessageAttachmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息附件
	Attachment []*Attachment `protobuf:"bytes,1,rep,name=attachment,proto3" json:"attachment,omitempty"`
	Total      int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListMessageAttachmentResponse) Reset() {
	*x = ListMessageAttachmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_box_im_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMessageAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageAttachmentResponse) ProtoMessage() {}

func (x *ListMessageAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_box_im_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageAttachmentResponse.ProtoReflect.Descriptor instead.
func (*ListMessageAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_box_im_proto_rawDescGZIP(), []int{9}
}

func (x *ListMessageAttachmentResponse) GetAttachment() []*Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *ListMessageAttachmentResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_box_im_proto protoreflect.FileDescriptor

var file_box_im_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x78, 0x2f, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x22, 0xbe, 0x01, 0x0a, 0x1e, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x74,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x6b, 0x0a, 0x1f, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xc2, 0x03, 0x0a, 0x0e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x26, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x74, 0x73,
	0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27,
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49,
	0x4d, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10,
	0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10,
	0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x06, 0x22, 0x8b, 0x02,
	0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x6c,
	0x61, 0x79, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x77, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x77, 0x69, 0x64,
	0x12, 0x29, 0x0a, 0x11, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x72, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x12, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x13, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x77, 0x0a, 0x18, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f,
	0x22, 0x81, 0x01, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x6d, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x74, 0x73, 0x6d,
	0x65, 0x2e, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x42, 0x5c, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x74, 0x73, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x62, 0x6f, 0x78, 0x42, 0x07, 0x49,
	0x4d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x65, 0x74, 0x73, 0x75, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x65, 0x62, 0x6f, 0x78, 0x2f,
	0x65, 0x62, 0x6f, 0x78, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x65, 0x62, 0x6f, 0x78, 0x70, 0x62, 0xf8, 0x01, 0x01, 0xa2, 0x02, 0x05, 0x45, 0x50, 0x42, 0x6f,
	0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_box_im_proto_rawDescOnce sync.Once
	file_box_im_proto_rawDescData = file_box_im_proto_rawDesc
)

func file_box_im_proto_rawDescGZIP() []byte {
	file_box_im_proto_rawDescOnce.Do(func() {
		file_box_im_proto_rawDescData = protoimpl.X.CompressGZIP(file_box_im_proto_rawDescData)
	})
	return file_box_im_proto_rawDescData
}

var file_box_im_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_box_im_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_box_im_proto_goTypes = []interface{}{
	(InstantMessage_MessageType)(0),         // 0: etsme.ebox.InstantMessage.MessageType
	(*ListConversationMessageRequest)(nil),  // 1: etsme.ebox.ListConversationMessageRequest
	(*ListConversationMessageResponse)(nil), // 2: etsme.ebox.ListConversationMessageResponse
	(*InstantMessage)(nil),                  // 3: etsme.ebox.InstantMessage
	(*Attachment)(nil),                      // 4: etsme.ebox.Attachment
	(*SendMessageRequest)(nil),              // 5: etsme.ebox.SendMessageRequest
	(*SendMessageResponse)(nil),             // 6: etsme.ebox.SendMessageResponse
	(*ReadMessageRequest)(nil),              // 7: etsme.ebox.ReadMessageRequest
	(*CancelSendMessageRequest)(nil),        // 8: etsme.ebox.CancelSendMessageRequest
	(*ListMessageAttachmentRequest)(nil),    // 9: etsme.ebox.ListMessageAttachmentRequest
	(*ListMessageAttachmentResponse)(nil),   // 10: etsme.ebox.ListMessageAttachmentResponse
}
var file_box_im_proto_depIdxs = []int32{
	3, // 0: etsme.ebox.ListConversationMessageResponse.messages:type_name -> etsme.ebox.InstantMessage
	0, // 1: etsme.ebox.InstantMessage.message_type:type_name -> etsme.ebox.InstantMessage.MessageType
	4, // 2: etsme.ebox.InstantMessage.attachment:type_name -> etsme.ebox.Attachment
	3, // 3: etsme.ebox.SendMessageRequest.message:type_name -> etsme.ebox.InstantMessage
	4, // 4: etsme.ebox.ListMessageAttachmentResponse.attachment:type_name -> etsme.ebox.Attachment
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_box_im_proto_init() }
func file_box_im_proto_init() {
	if File_box_im_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_box_im_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConversationMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConversationMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstantMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMessageAttachmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_box_im_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMessageAttachmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_box_im_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_box_im_proto_goTypes,
		DependencyIndexes: file_box_im_proto_depIdxs,
		EnumInfos:         file_box_im_proto_enumTypes,
		MessageInfos:      file_box_im_proto_msgTypes,
	}.Build()
	File_box_im_proto = out.File
	file_box_im_proto_rawDesc = nil
	file_box_im_proto_goTypes = nil
	file_box_im_proto_depIdxs = nil
}
